### ISSUE TITLE
mail format 

### ISSUE THREAD

**Issue by bphd** [costasf-glitch/OutlookMessageSearch#1]
Do you know what format use Microsoft to store its mails in OST/PST files? HTML/EML/MESSAGE/etc.

**Comment by costasf-glitch** [comment]
General question.  Not relevant to the program in this git repository.  The PST format is documented [here](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-pst/141923d5-15ab-4ef1-a524-6dce75aae546).
